---
title: "scorecards_data_processing"
---

```{r Install packages, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}
# Install and load packages ----------------------------------------
suppressMessages({
  library(readxl)
  library(writexl)
  library(plyr)
  library(dplyr)
  library(data.table)
  library(zoo)
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  library(shinyWidgets)
  library(htmlwidgets)
  library(lubridate)
  library(tcltk)
  library(tidyverse)
  library(plotly)
  library(knitr)
  library(kableExtra)
  library(leaflet)
  library(grid)
  library(gridExtra)
  library(eeptools)
  library(ggQC)
  library(zipcode)
  library(utils)
  library(scales)
  library(chron)
  library(bupaR)
  library(shiny)
  library(DT)
  library(DiagrammeR)
  library(shinyalert)
  library(edeaR)
  library(processmapR)
  library(processmonitR)
  library(processanimateR)
  library(tidyr)
  library(lubridate)
  library(RColorBrewer)
  library(DiagrammeR)
  library(ggplot2)
  library(leaflet)
  library(readr)
  library(highcharter)
  library(ggforce) # for 'geom_arc_bar'
  library(packcircles) # for packed circle graph
  library(viridis)
  library(ggiraph)
  library(treemapify)
  library(treemap)
  library(broom)
  library(extrafont)
  library(tis) # for US holidays
  library(vroom)
  library(sjmisc)
  library(tools)
  library(here)
  library(shinyBS)
  library(shinyscreenshot)
  library(fasttime)
  library(shinycssloaders)
  library(assertr)
})
```


```{r Reference files importing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

# Import all reference / mapping files needed
site_path <- here("Data") # Set path to new data (raw data)
site_mapping <- read_excel(paste0(site_path,"/MSHS Scorecards Target Mapping.xlsx"), 
                           sheet = "Site_New",  col_names = TRUE, na = c("", "NA")) # Premier site-service mapping

report_date_mapping <- read_excel(paste0(site_path,"/MSHS Scorecards Target Mapping.xlsx"), 
                           sheet = "Report Dates",  col_names = TRUE, na = c("", "NA")) # Premier reporting-dashboard date mapping 

target_mapping <- read_excel(paste0(site_path,"/MSHS Scorecards Target Mapping.xlsx"), 
                           sheet = "Target",  col_names = TRUE, na = c("", "NA")) # Metrics target mapping

metric_group_mapping <- read_excel(paste0(site_path,"/MSHS Scorecards Target Mapping.xlsx"), 
                           sheet = "Metric Group",  col_names = TRUE, na = c("", "NA")) # Metric group mapping
metric_group_mapping <- metric_group_mapping %>% # Processing metric group mapping file
  pivot_longer(
    6:length(metric_group_mapping),
    names_to = "Service",
    values_to = "Inclusion"
  ) %>%
  filter(!is.na(Inclusion))

cost_rev_mapping <- read_excel(paste0(site_path,"/MSHS Scorecards Target Mapping.xlsx"), 
                           sheet = "Cost and Rev Mapping",  col_names = TRUE, na = c("", "NA")) # Metric group mapping

```


```{r data importing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

# Import up-to-date data files for all data sources 
data_dir <- here("Data/Other") 

data_list <- list.files(path = data_dir, full.names=TRUE) # List out data files in data folder 

data_raw <- lapply(data_list, function(filename){ # Import in data files 
  print(paste("Importing",filename,sep = " "))
  read_excel(filename, col_names = TRUE, na = c("", "NA"))
})

data_names <- lapply(data_list, function(name){ # Extract data file names 
  gsub(".*Other/*(.*?) *.xlsx.*", "\\1", name)
  })

names(data_raw) <- as.vector(data_names) # Set data file names in data list

```


```{r data processing standard functions, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

dttm <- function(x) {
  as.POSIXct(x,format="%m/%d/%Y",tz=Sys.timezone(),origin = "1970-01-01")
}

processed_df_cols <- c("Service","Site","Metric_Group","Metric_Name","Premier_Reporting_Period",
                       "Reporting_Month","value_rounded","Target","Status") # All columns needed in final merged data set

```


```{r Budget to Actual (Salary + Non Salary)data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_budget_actual <- data_raw$`Budget to Actual`


## Budget to Actual data pre-processing
budget_actual_df <- raw_budget_actual %>%
  mutate(Month_Var = ifelse(`Month Budget` == "Not Received", " ", 
                            round(as.numeric(`Month Budget`) - as.numeric(`Month Actual`))),
         Metric_Name = ifelse(`Account Category Desc2` == "Salary", 
                              "Budget to Actual Variance - Labor", "Budget to Actual Variance - Non Labor")) %>%
  group_by(Service, Site, Metric_Name, Month) %>%
  summarise(Month_Var= sum(as.numeric(Month_Var), na.rm = TRUE)) %>%
  pivot_wider(
    names_from = Metric_Name,
    values_from = Month_Var) %>%
  select(1:5) %>%
  mutate(`Budget to Actual Variance - Total` = 
           `Budget to Actual Variance - Labor` + `Budget to Actual Variance - Non Labor`)

## Calculate Target and Status
budget_actual_target <- raw_budget_actual %>%
  group_by(Service, Site, Month) %>%
  summarise(Budget_Total = sum(as.numeric(`Month Budget`), na.rm = TRUE)) 


budget_actual_df <- merge(budget_actual_df, budget_actual_target)
budget_actual_df <- budget_actual_df %>% 
  mutate(Target = round(`Budget to Actual Variance - Total`/Budget_Total,2),
         Status = ifelse(Target >= 0, "Green", ifelse(Target < -0.02, "Red", "Yellow"))) %>%
  pivot_longer(4:7,
               names_to = "Metric_Name",
               values_to = "value_rounded") %>%
  mutate(Metric_Group = "Budget to Actual",
         Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"),
         Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y")) %>%
  filter(!is.na(Reporting_Month))

budget_actual_df$Metric_Name_Submitted <- metric_group_mapping$Metric_Name[match(budget_actual_df$Metric_Name, metric_group_mapping$Metric_Name_Submitted)]
budget_actual_df <- budget_actual_df %>% 
  mutate(Metric_Name = ifelse(is.na(Metric_Name_Submitted), Metric_Name, Metric_Name_Submitted))

### Subset processed data for merge
budget_actual_df_merge <- budget_actual_df[,processed_df_cols] 

compiled_data_list <- list(budget_actual_df_merge = budget_actual_df_merge)

```


```{r CM KPI data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_cm_df <- data_raw$`CM KPI`


## Security CM KPI data pre-processing 
cm_kpi_df <- raw_cm_df %>%
  mutate_at(4:length(raw_cm_df), as.numeric) %>%
  pivot_longer(
    4:length(raw_cm_df), 
    names_to = "Metric_Name_Submitted",
    values_to = "value") %>%
  mutate(Service = "Engineering",
         Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
         Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"),
         value_rounded = value)

cm_kpi_df$Metric_Group <- metric_group_mapping$Metric_Group[match(cm_kpi_df$Metric_Name_Submitted, metric_group_mapping$Metric_Name_Submitted)]
cm_kpi_df$Metric_Name <- metric_group_mapping$Metric_Name[match(cm_kpi_df$Metric_Name_Submitted, metric_group_mapping$Metric_Name_Submitted)]

### Create Target Variance Column
cm_kpi_target_status <- merge(cm_kpi_df[, c("Service","Site","Metric_Group","Metric_Name","Reporting_Month","value_rounded")],
                              target_mapping, 
                              by = c("Service","Site","Metric_Group","Metric_Name"),
                              all = TRUE)

cm_kpi_target_status <- cm_kpi_target_status %>%
    mutate(Variance = between(value_rounded, Range_1, Range_2)) %>% # Target mapping
  filter(Variance == TRUE)

cm_kpi_df_final <- merge(cm_kpi_df, cm_kpi_target_status[,c("Service","Site","Metric_Group","Metric_Name","Reporting_Month","Target","Status")],
                       all = TRUE)


# Subset processed data for merge 
cm_kpi_df_final <- cm_kpi_df_final[,processed_df_cols]

compiled_data_list$cm_kpi_df_final <- cm_kpi_df_final

```


```{r Cost and Revenue data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_cost_rev_df <- data_raw$`Cost and Revenue`


# Cost and Revenue data pre-processing
cost_rev_df <- raw_cost_rev_df %>%
  select(-Notes) %>%
  mutate(
    `Actual Revenue` = as.numeric(`Actual Revenue`),
    rev_per_census = round(`Actual Revenue`/`Census Days`, 2),
    budget_actual_var = as.numeric(ifelse(is.na(`Revenue Budget`), "", round(`Revenue Budget` - `Actual Revenue`, 2))),
    Target = ifelse(Metric == "Revenue from R&C (Includes Foregone)", round(budget_actual_var/`Revenue Budget`,2), ""),
    Status = ifelse((is.na(Target) | Target == ""), "", ifelse(Target <= 0, "Green", ifelse(Target > 0.02, "Red", "Yellow")))) %>%
  pivot_longer(
    6:9,
    names_to = "Metric_Name_Submitted",
    values_to = "value") %>%
  mutate(
        Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
        Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"),
        value_rounded = round(value, 2))
  
cost_rev_df_final <- merge(cost_rev_df, cost_rev_mapping, 
                           by = c("Metric", "Metric_Name_Submitted"))


# Subset processed data for merge 
cost_rev_df_merge <- cost_rev_df_final[,processed_df_cols] 

compiled_data_list$cost_rev_df_merge <- cost_rev_df_merge 

```


```{r Dep Rport Builder (Premier) data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

# Import productivity data for depts excluding Nursing and Radiology 
raw_prod_df <- data_raw$`Dept Report Builder`
raw_prod_df <- raw_prod_df %>% select(!`Entity Time Period Desc`)

## Productivity data pre-processing
### Aggregate reporting period columns
prod_df <- raw_prod_df %>% 
  mutate(id = seq_len(n())) %>% 
  melt(id.var = c('Corporation Code','Corporation Name', 'Entity Code', 'Entity', 'Department Reporting Definition ID',
                  'Department Reporting Definition Name', 'Key Volume', 'Mapped Facility Cost Centers', 'id'), na.rm = F) %>% 
  select(-c('id'))


### Process Reporting Period to Reporting Month
prod_df$variable <- gsub("\\..*","", prod_df$variable) # Remove underscores at end of reporting period
names(prod_df)[names(prod_df) == 'variable'] <- 'Premier_Reporting_Period' # Rename Reporting Period column
prod_df <- prod_df %>%
  mutate(Reporting_Month_Start = as.Date(dttm(gsub(" .*$", "", Premier_Reporting_Period))))

prod_df_final <- prod_df %>% # Fill in Metric name in a column
  mutate(Metrics = as.numeric(value),
         Metrics = ifelse(is.na(Metrics), value, ""),
         Metrics = ifelse(Metrics == "", NA, Metrics)) %>%
  fill(Metrics) %>%
  filter(!is.na(`Corporation Code`)) %>%
  unique()


# Import productivity data fo Nursing and Radiology 
raw_prod_nursing_rad_df <- data_raw$`Dept Report Builder_nursing_radiology`
raw_prod_nursing_rad_df <- raw_prod_nursing_rad_df %>% select(!`Entity Time Period Desc`)


## Productivity data pre-processing
### Aggregate reporting period columns
prod_nursing_rad_df <- raw_prod_nursing_rad_df %>% 
  mutate(id = seq_len(n())) %>% 
  melt(id.var = c('Corporation Code','Corporation Name', 'Entity Code', 'Entity', 'Department Reporting Definition ID',
                  'Department Reporting Definition Name', 'Key Volume', 'Mapped Facility Cost Centers', 'id'), na.rm = F) %>% 
  select(-c('id'))


### Process Reporting Period to Reporting Month
prod_nursing_rad_df$variable <- gsub("\\..*","", prod_nursing_rad_df$variable) # Remove underscores at end of reporting period
names(prod_nursing_rad_df)[names(prod_nursing_rad_df) == 'variable'] <- 'Premier_Reporting_Period' # Rename Reporting Period column
prod_nursing_rad_df <- prod_nursing_rad_df %>%
  mutate(Reporting_Month_Start = as.Date(dttm(gsub(" .*$", "", Premier_Reporting_Period))))

prod_nursing_rad_df_final <- prod_nursing_rad_df %>% # Fill in Metric name in a column
  mutate(Metrics = as.numeric(value),
         Metrics = ifelse(is.na(Metrics), value, ""),
         Metrics = ifelse(Metrics == "", NA, Metrics)) %>%
  fill(Metrics) %>%
  filter(!is.na(`Corporation Code`)) %>%
  unique()


# Merge two data imports and exclude duplicates 
prod_df_merged <- rbind(prod_df_final, prod_nursing_rad_df_final)
prod_df_merged <- prod_df_merged %>%
  unique()


## Map Site and Service Group
prod_df_all <- merge(prod_df_merged, site_mapping[,c("DEFINITION.CODE","KEY.VOLUME","SITE", "Balanced.Scorecards.Groupings")], 
                              by.x = c("Department Reporting Definition ID", "Key Volume"),
                              by.y = c("DEFINITION.CODE", "KEY.VOLUME"), all.x = TRUE)

names(prod_df_all)[names(prod_df_all) == "Balanced.Scorecards.Groupings"] <- "Service"
names(prod_df_all)[names(prod_df_all) == "SITE"] <- "Site"


prod_df_all <- prod_df_all %>% # Process Metric Group column
  filter(!is.na(Service)) %>%
  mutate(Metric_Name = trim(gsub("-.*","", Metrics)),
         Metric_Group = ifelse(grepl("Overtime", Metric_Name), "Overtime Hours", "Productivity"),
         value_rounded = round(parse_number(value),2))

### Map Premier Reporting Period -> Dashboard Month 
report_date_mapping <- report_date_mapping %>%
  mutate(`Report Data Updated until` = format(as.Date(`Report Data Updated until`, "%m/%d/%Y"), "%m/%d/%Y"),
         `Report Release Date` = format(as.Date(`Report Release Date`, "%m/%d/%Y"), "%m/%d/%Y"),
         `Dashboard Month` = format(as.Date(`Dashboard Month`, "%m/%d/%Y"), "%m/%d/%Y"))

report_data <- as.data.frame(report_date_mapping$`Report Data Updated until`)
report_data <- col_concat(report_data, sep = "|")
report_data <- paste(report_data, collapse = "|")

prod_df_all <- prod_df_all %>% filter(grepl(report_data, Premier_Reporting_Period))
prod_df_all <- prod_df_all %>% separate(Premier_Reporting_Period, c("Report_Start","Report_End"), sep = " - ", remove = FALSE)
prod_df_all$Reporting_Month_Ref <- report_date_mapping$`Dashboard Month`[match(prod_df_all$`Report_End`,report_date_mapping$`Report Data Updated until`)]
prod_df_all$Reporting_Month_Ref <- as.Date(prod_df_all$Reporting_Month_Ref, format = "%m/%d/%Y")

prod_df_all <- prod_df_all[, !(names(prod_df_all) %in% c("Report_Start","Report_End"))]
prod_df_all <- prod_df_all %>% unique()


## Calculate aggregate Overtime % and Productivity Index for Nursing and Imaging
prod_df_aggregate <- prod_df_all %>%
  group_by(Service, Site, Metric_Group, Metric_Name, Premier_Reporting_Period, Reporting_Month_Ref) %>%
  summarise(value_rounded = round(mean(value_rounded, na.rm = TRUE),2)) %>%
  filter(Metric_Name != "Total Target Worked FTE") %>%
  filter(!(Service %in% c("Nursing","Imaging") & 
             Metric_Name %in% c("Overtime Percent of Paid Hours","Worked Hours Productivity Index")))


nursing_rad_metric_calc <- prod_df_all %>% # Calculate Productivity and Overtime % separately 
  filter(Service %in% c("Nursing","Imaging")) %>%
  filter(Metric_Name %in% c("Total Target Worked FTE","Actual Worked FTE",
                            "Overtime Hours", "Total Paid hours")) %>%
  group_by(Service, Site, Metric_Name, Premier_Reporting_Period, Reporting_Month_Ref) %>%
  summarise(value_rounded = round(sum(value_rounded, na.rm = TRUE),2)) %>%
  pivot_wider(names_from = Metric_Name,
              values_from = value_rounded) %>%
  mutate(`Worked Hours Productivity Index` = round(`Total Target Worked FTE`/`Actual Worked FTE`,2),
         `Overtime Percent of Paid Hours` = round(`Overtime Hours`/`Total Paid hours`,2)) %>%
  pivot_longer(5:9,
               names_to = "Metric_Name",
               values_to = "value_rounded") %>%
  filter(Metric_Name %in% c("Worked Hours Productivity Index","Overtime Percent of Paid Hours")) %>%
  mutate_at(vars(value_rounded), ~replace(., is.nan(.), 0)) %>%
  mutate(Metric_Group = ifelse(Metric_Name == "Worked Hours Productivity Index", "Productivity", "Overtime Hours"))


prod_df_aggregate_all <- bind_rows(prod_df_aggregate, nursing_rad_metric_calc) # Merge newly calculated productivity index and overtime % for nursing and radiology 

prod_df_aggregate_all$Metric_Name <- metric_group_mapping$Metric_Name[match(prod_df_aggregate_all$Metric_Name, 
                                                                            metric_group_mapping$Metric_Name_Submitted)] # Map final Metric_Name


### Create Target Variance Column
prod_target_status <- merge(prod_df_aggregate_all[, c("Service","Site","Metric_Name","Reporting_Month_Ref","value_rounded")],
                            target_mapping, by = c("Service","Site","Metric_Name"),
                            all = TRUE)

prod_target_status <- prod_target_status %>%
  mutate(Variance = between(value_rounded, Range_1, Range_2)) %>% # Target mapping
  filter(Variance == TRUE)

prod_df_final <- merge(prod_df_aggregate_all, prod_target_status[,c("Service","Site","Metric_Name","Reporting_Month_Ref","Target","Status")],
                       all = TRUE)

prod_df_final$Reporting_Month <- format(as.Date(prod_df_final$Reporting_Month_Ref, format = "%Y-%m-%d"),"%m-%Y")
prod_df_final$Reporting_Month_Ref <- NULL

prod_df_final$Premier_Reporting_Period <- sub(".*- ", "", prod_df_final$Premier_Reporting_Period)

# Subset processed data for merge 
prod_df_merge <- prod_df_final[,processed_df_cols] 

compiled_data_list$prod_df_merge <- prod_df_merge 

```


```{r Dep Rport Builder (Nursing and Radiology) data import, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_prod_nursing_rad_df <- data_raw$`Dept Report Builder_nursing_radiology`
raw_prod_nursing_rad_df <- raw_prod_nursing_rad_df %>% select(!`Entity Time Period Desc`)


## Productivity data pre-processing
### Aggregate reporting period columns
prod_nursing_rad_df <- raw_prod_nursing_rad_df %>% 
  mutate(id = seq_len(n())) %>% 
  melt(id.var = c('Corporation Code','Corporation Name', 'Entity Code', 'Entity', 'Department Reporting Definition ID',
                  'Department Reporting Definition Name', 'Key Volume', 'Mapped Facility Cost Centers', 'id'), na.rm = F) %>% 
  select(-c('id'))


### Process Reporting Period to Reporting Month
prod_nursing_rad_df$variable <- gsub("\\..*","", prod_nursing_rad_df$variable) # Remove underscores at end of reporting period
names(prod_nursing_rad_df)[names(prod_nursing_rad_df) == 'variable'] <- 'Premier_Reporting_Period' # Rename Reporting Period column
prod_nursing_rad_df <- prod_nursing_rad_df %>%
  mutate(Reporting_Month_Start = as.Date(dttm(gsub(" .*$", "", Premier_Reporting_Period))))

prod_nursing_rad_df_final <- prod_nursing_rad_df %>% # Fill in Metric name in a column
  mutate(Metrics = as.numeric(value),
         Metrics = ifelse(is.na(Metrics), value, ""),
         Metrics = ifelse(Metrics == "", NA, Metrics)) %>%
  fill(Metrics) %>%
  filter(!is.na(`Corporation Code`)) %>%
  unique()

```


```{r Disruption and Issues data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_disruptions_df <- data_raw$`Disruptions and Issues`


## Discruption and Issues data pre-processing
disruptions_df <- raw_disruptions_df %>%
  group_by(Service, Site, Month) %>%
  summarise(value_rounded = round(mean(`Total Disruptions/Issues`, na.rm = TRUE),1)) %>%
  mutate(
    Metric_Group = "Total Disruptions and Equipment Issues",
    Metric_Name = "Daily Avg. # of Disruptions and Issues",
    Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
    Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"),
    # Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
    Target = "",
    Status = "")


# Subset processed data for merge 
disruptions_df_merge <- disruptions_df[,processed_df_cols] 

compiled_data_list$disruptions_df_merge <- disruptions_df_merge

```


```{r Finance overtime data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_finance_df <- data_raw$`Finance Overtime`


## Finance overtime data pre-processing 
finance_df_final <- raw_finance_df %>%
  mutate(Reporting_Month = format(as.Date(`Associated Dashboard Month`, format = "%Y-%m-%d"),"%m-%Y"),
         value_rounded = round(as.numeric(Value)),
         Metric_Group = "Overtime Hours")

finance_target_status <- merge(finance_df_final, target_mapping, by = c("Service","Site","Metric_Name")) # Target mapping

finance_target_status <- finance_target_status %>%
  mutate(Variance = between(value_rounded, Range_1, Range_2)) %>%
  filter(Variance == TRUE) 

finance_df_final <- merge(finance_df_final, finance_target_status[,c("Service","Site","Metric_Name","Target","Status")],
                          all = TRUE)

finance_df_final <- unique(finance_df_final) # Why are duplicates created from merging operation above?

finance_df_final$Premier_Reporting_Period <- format(finance_df_final$`Associated Dashboard Month`, "%b %Y")

# Subset processed data for merge 
finance_df_merge <- finance_df_final[,processed_df_cols] 

compiled_data_list$finance_df_merge <- finance_df_merge

```


```{r Incidents Metric data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_incidents_df <- data_raw$`Incidents Metric`


## Incidents data processing
incidents_metrics <- c("Incident Reports",
                       "Security Assistance Calls",
                       "Security Officer Injured",
                       "Security Alert - Emergency Room",
                       "Patient Searched",
                       "Security Alert",
                       "Security Escorts")

incidents_df <- raw_incidents_df[, 1:5] %>%
  filter(Metric %in% incidents_metrics) %>%
  mutate(
    Metric_Group = "Incident Reports",  
    Metric_Name = Metric,
    Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
    Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"),
    value_rounded = Occurences,
    Target = "",
    Status = "")

# Subset processed data for merge 
incidents_df_merge <- incidents_df[,processed_df_cols] 

compiled_data_list$incidents_df_merge <- incidents_df_merge 

```


```{r KPIs data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_KPIs_df <- data_raw$KPIs


## KPIs processing
KPIs_df <- raw_KPIs_df %>%
  # filter(!is.na(Metric_Group)) %>%
   mutate(
    Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
    Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"),
    value_rounded = round(Number))


### Map Metric Group and Name 
KPIs_df <- merge(KPIs_df, metric_group_mapping[c("Metric_Group","Metric_Name","Metric_Name_Submitted")], 
                 by.x = c("Metric"),
                 by.y = c("Metric_Name_Submitted"))

KPIs_df$Metric <- NULL


### Create Target Variance Column
KPIs_target_status <- merge(KPIs_df[, c("Service","Site","Metric_Name","Reporting_Month","value_rounded")],
                            target_mapping, 
                            by.x = c("Service","Site","Metric_Name"),
                            by.y = c("Service","Site","Metric_Name"),
                            all = TRUE)

KPIs_target_status <- KPIs_target_status %>%
  mutate(Variance = between(value_rounded, Range_1, Range_2)) %>% # Target mapping
  filter(Variance == TRUE)

KPIs_df_final <- merge(KPIs_df, 
                       KPIs_target_status[,c("Service","Site","Metric_Group","Metric_Name","Reporting_Month","Target","Status")],
                       all = FALSE)


# Subset processed data for merge 
KPIs_df_merge <- KPIs_df_final[,processed_df_cols]

compiled_data_list$KPIs_df_merge <- KPIs_df_merge

```


```{r Press Geney data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

```


```{r TAT - EVS data processing, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

raw_TAT_EVS_df <- data_raw$`TAT - EVS`


## TAT - EVS processing 
raw_TAT_EVS_df[,5:length(raw_TAT_EVS_df)] <- sapply(raw_TAT_EVS_df[,5:length(raw_TAT_EVS_df)], as.numeric)
TAT_EVS_df <- raw_TAT_EVS_df %>%
  mutate(`% Isolation Turns` = round(`Isolation Requests` / (`Isolation Requests` + `Non-Isolation Requests`),2),
         `% Non-Isolation Turns` = round(`Non-Isolation Requests` / (`Isolation Requests` + `Non-Isolation Requests`),2)) %>%
  pivot_longer(5:12,
               names_to = "Metric_Name_Submitted",
               values_to = "value_rounded") %>%
  mutate(value_rounded = round(value_rounded),
        Premier_Reporting_Period = format(as.Date(Month, format = "%Y-%m-%d"),"%b %Y"),
         Reporting_Month = format(as.Date(Month, format = "%Y-%m-%d"),"%m-%Y"))

TAT_EVS_df <- merge(TAT_EVS_df, metric_group_mapping[c("Metric_Group","Metric_Name","Metric_Name_Submitted")],
                    by = c("Metric_Name_Submitted"))

### Create Target Variance Column
TAT_EVS_target_status <- merge(TAT_EVS_df[, c("Service","Site","Metric_Group", "Metric_Name","Reporting_Month","value_rounded")],
                            target_mapping, 
                            by.x = c("Service","Site","Metric_Group", "Metric_Name"),
                            by.y = c("Service","Site","Metric_Group", "Metric_Name"),
                            all = TRUE)

TAT_EVS_target_status <- TAT_EVS_target_status %>%
  mutate(Variance = between(value_rounded, Range_1, Range_2)) %>% # Target mapping
  filter(Variance == TRUE)

TAT_EVS_df_final <- merge(TAT_EVS_df, 
                          TAT_EVS_target_status[,c("Service","Site","Metric_Group","Metric_Name","Reporting_Month","Target","Status")],
                          all = FALSE)

# Subset processed data for merge 
TAT_EVS_df_merge <- TAT_EVS_df_final[,processed_df_cols]

compiled_data_list$TAT_EVS_df_merge <- TAT_EVS_df_merge
  
```


```{r Merging of all processed data, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

## Align all column types 
for (i in seq_along(compiled_data_list)){
  compiled_data_list[[i]]$Target <- as.numeric(compiled_data_list[[i]]$Target)
  compiled_data_list[[i]]$value_rounded <- as.numeric(compiled_data_list[[i]]$value_rounded)
}

## Merge all processed data frames
compiled_df <- bind_rows(compiled_data_list)

compiled_df$Reporting_Month_Ref <- as.Date(paste('01', as.yearmon(compiled_df$Reporting_Month, "%m-%Y")), format='%d %b %Y')


## Create empty rows for missing sites and metrics
### Process data to include missing sites for each metric 
# sites_inc <- c("MSB","MSBI","MSH","MSM","MSQ","MSW","NYEE")
# 
# compiled_df <- compiled_df %>%
#   mutate(common_id = paste0(Service, Metric_Group, Metric_Name))
# 
# missing <- expand.grid(
#   # Service = unique(compiled_df$Service),
#   # Site = sites_inc, # Fill missing sites
#   # Metric_Group = unique(compiled_df$Metric_Group),
#   # Metric_Name = unique(compiled_df$Metric_Name),
#   common_id = unique(compiled_df$common_id),
#   Site = unique(compiled_df$Site),
#   Reporting_Month = unique(compiled_df$Reporting_Month))
# 
# missing <- merge(missing, compiled_df, by = c("common_id","Reporting_Month"), all = TRUE)
# 
# compiled_df_final <- merge(missing, compiled_df, by = c("Site","Reporting_Month","common_id"), all.x = TRUE)
# compiled_df_final$Reporting_Month_Ref <- as.Date(paste('01', as.yearmon(compiled_df_final$Reporting_Month, "%m-%Y")), format='%d %b %Y')

```


```{r Create repo of compiled data, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}

## Export repo of compiled and processed data
saveRDS(compiled_df, "Data/metrics_final_df.rds")

```

