--------------------------------------------------------
--  DDL for View BSC_CURRENT_FINANCE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "OAO_PRODUCTION"."BSC_CURRENT_FINANCE_VIEW" ("FUNCTION", "EXPTYPE", "MONTH", "MTD_TARGET", "MTD_ACTUAL", "YTD_TARGET", "YTD_ACTUAL", "MTD_VARIANCE_TO_TARGET", "MTD_PERCENT_VARIANCE", "YTD_VARIANCE_TO_TARGET", "YTD_PERCENT_VARIANCE") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT a."FUNCTION",a."EXPTYPE",a."MONTH",a."MTD_TARGET",a."MTD_ACTUAL",a."YTD_TARGET",a."YTD_ACTUAL", (a.MTD_TARGET - a.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,
        ROUND(((a.MTD_TARGET - a.MTD_ACTUAL)/NULLIF(a.MTD_TARGET,0)),5) AS MTD_PERCENT_VARIANCE,
        (a.YTD_TARGET - a.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
        ROUND(((a.YTD_TARGET - a.YTD_ACTUAL)/NULLIF(a.YTD_TARGET,0)),5) AS YTD_PERCENT_VARIANCE
FROM (
    SELECT Function, EXPTYPE, Month,
    SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
    SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
    SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
    SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
    FROM BSC_FINANCE_TABLE_VIEW
    WHERE EXPTYPE IN ('Salaries', 'Supplies')
    GROUP BY Function, EXPTYPE, Month) a
UNION
/* Supplies and Salaries Combined for  YTD , MTD, Variance and Percent Variance */
SELECT b."FUNCTION",b."EXPTYPE",b."MONTH",b."MTD_TARGET",b."MTD_ACTUAL",b."YTD_TARGET",b."YTD_ACTUAL", (b.MTD_TARGET - b.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,
        ROUND(((b.MTD_TARGET - b.MTD_ACTUAL)/NULLIF(b.MTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE,
        (b.YTD_TARGET - b.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
        ROUND(((b.YTD_TARGET - b.YTD_ACTUAL)/NULLIF(b.YTD_TARGET, 0)),5) AS YTD_PERCENT_VARIANCE
FROM (
    SELECT Function, 'Total Expenses' AS EXPTYPE,Month,
    SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
    SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
    SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
    SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
    FROM BSC_FINANCE_TABLE_VIEW
    WHERE EXPTYPE IN ('Salaries', 'Supplies')
    GROUP BY Function, Month) b
UNION
SELECT c."FUNCTION",c."EXPTYPE",c."MONTH",c."MTD_TARGET",c."MTD_ACTUAL",c."YTD_TARGET",c."YTD_ACTUAL", (c.MTD_TARGET - c.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,
        ROUND(((c.MTD_TARGET - c.MTD_ACTUAL)/NULLIF(c.MTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE,
        (c.YTD_TARGET - c.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
        ROUND(((c.YTD_TARGET - c.YTD_ACTUAL)/NULLIF(c.YTD_TARGET, 0)),5) AS YTD_PERCENT_VARIANCE
FROM (
    SELECT Function,
        CASE
          WHEN SUPPLY_CATGEGORY = 'Agency' then 'Agency/Temp Help Dollars'
          ELSE 'OT Dollars'
        END EXPTYPE,
        Month,
        SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
        SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
        SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
        SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
    FROM BSC_FINANCE_TABLE_VIEW
    WHERE SUPPLY_CATGEGORY IN ( 'Agency','OT')   /* EXPTYPE IN ('Salaries', 'Supplies') */
    GROUP BY Function, Month,SUPPLY_CATGEGORY) c
UNION
SELECT d.Function,
       'Worked Hours Productivity Index' AS EXPTYPE,
       d.MONTH,
       1.00 AS MTD_TARGET,
       d.MTD_ACTUAL,
       1.00 AS YTD_TARGET,
       d.YTD_ACTUAL,
       d.MTD_ACTUAL - 1.00 AS MTD_VARIANCE_TO_TARGET,
       d.MTD_ACTUAL - 1.00 AS MTD_PERCENT_VARIANCE,
       d.YTD_ACTUAL - 1.00 AS YTD_VARIANCE_TO_TARGET,
       d.YTD_ACTUAL - 1.00 AS YTD_PERCENT_VARIANCE
FROM (
SELECT *
FROM(
    SELECT SERVICE AS Function,
          METRIC_NAME_SUBMITTED AS EXPTYPE,
          VALUE,
          REPORTING_MONTH AS MONTH
    FROM BSC_SYSTEM_WIDE_PRODUCTIVITY_FINANCE
    )
PIVOT(
 SUM(VALUE)
 FOR EXPTYPE IN ('Worked Hours Productivity Index (FYTD)' YTD_ACTUAL,'Worked Hours Productivity Index' MTD_ACTUAL))) d
 UNION
SELECT DISTINCt y.FUNCTION, y.EXPTYPE, y.MONTH, y.MTD_TARGET, y.MTD_ACTUAL, x.YTD_TARGET, x.YTD_ACTUAL, y.MTD_VARIANCE_TO_TARGET, y.MTD_PERCENT_VARIANCE, x.YTD_VARIANCE_TO_TARGET, x.YTD_PERCENT_VARIANCE FROM
(
SELECT DISTINCT c.SERVICE AS FUNCTION, c.METRIC_NAME_SUMMARY AS EXPTYPE, c.REPORTING_MONTH AS MONTH, e.TARGET AS MTD_TARGET, c.VALUE AS MTD_ACTUAL, c.VALUE - e.TARGET AS MTD_VARIANCE_TO_TARGET, c.VALUE - e.TARGET AS MTD_PERCENT_VARIANCE
FROM(
    SELECT b.SERVICE, a.SITE, a.REPORTING_MONTH, a.METRIC_NAME_SUBMITTED, b.METRIC_NAME_SUMMARY, a.VALUE, b.METRIC_UNIT FROM SUMMARY_REPO a
    LEFT JOIN BSC_MAPPING_TABLE b on a.SERVICE = b.SERVICE AND a.METRIC_NAME_SUBMITTED = b.METRIC_NAME_SUBMITTED
    WHERE a.SITE = 'SYSTEM' and a.METRIC_NAME_SUBMITTED NOT LIKE '%(FYTD)'
) c LEFT JOIN BSC_TARGET_STATUS e on c.SERVICE = e.SERVICE AND c.METRIC_NAME_SUBMITTED = e.METRIC_NAME_SUBMITTED AND c.SITE = e.SITE WHERE e.SITE = 'SYSTEM'
) y
LEFT JOIN(
SELECT DISTINCt f.SERVICE AS FUNCTION, f.METRIC_NAME_SUMMARY AS EXPTYPE, f.REPORTING_MONTH AS MONTH, g.TARGET AS YTD_TARGET, f.VALUE AS YTD_ACTUAL, f.VALUE - g.TARGET AS YTD_VARIANCE_TO_TARGET, f.VALUE - g.TARGET AS YTD_PERCENT_VARIANCE
FROM(
    SELECT b.SERVICE, a.SITE, a.REPORTING_MONTH, b.METRIC_NAME_SUBMITTED, b.METRIC_NAME_SUMMARY, a.VALUE, b.METRIC_UNIT FROM SUMMARY_REPO a
    RIGHT JOIN BSC_MAPPING_TABLE b on a.SERVICE = b.SERVICE AND a.METRIC_NAME_SUBMITTED = CONCAT(b.METRIC_NAME_SUBMITTED, ' (FYTD)')
    WHERE a.SITE = 'SYSTEM' and a.METRIC_NAME_SUBMITTED LIKE '%(FYTD)'
) f LEFT JOIN BSC_TARGET_STATUS g on f.SERVICE = g.SERVICE AND f.METRIC_NAME_SUBMITTED = g.METRIC_NAME_SUBMITTED AND f.SITE = g.SITE and g.SITE = 'SYSTEM'
) x on y.FUNCTION = x.FUNCTION AND y.EXPTYPE = x.EXPTYPE AND y.MONTH = x.MONTH
UNION /*Lab KPI Metrics */
SELECT m.FUNCTION,
       m.EXPTYPE,
       m.MONTH,
       m.MTD_TARGET,
       m.MTD_ACTUAL,
       y.YTD_TARGET,
       y.YTD_ACTUAL,
       m.MTD_VARIANCE_TO_TARGET,
       m.MTD_PERCENT_VARIANCE,
       y.YTD_VARIANCE_TO_TARGET,
       y.YTD_PERCENT_VARIANCE
FROM (SELECT d.SERVICE AS FUNCTION, /* MTD Metric Lab */
           d.METRIC_NAME_SUBMITTED AS EXPTYPE,
           d.REPORTING_MONTH AS MONTH,
           t.TARGET AS MTD_TARGET,
           d.VALUE AS MTD_ACTUAL,
           d.VALUE - t.TARGET AS MTD_VARIANCE_TO_TARGET,
           d.VALUE - t.TARGET AS MTD_PERCENT_VARIANCE
        FROM ( SELECT * FROM BSC_LAB_KPI_SYSTEM_METRICS
               WHERE SITE = 'SYSTEM' AND
                     METRIC_NAME_SUBMITTED IN ('Cytology GYN Volume','Cytology GYN % (=< 8 days)','Breast Biopsy % (=< 3 days)','Breast Biopsy Volume','Breast Large/Resection Volume','Breast Large/Resection % (=< 5 days)')) d
        LEFT JOIN  (SELECT * FROM BSC_TARGET_STATUS
                    WHERE SITE = 'SYSTEM' AND
                        METRIC_NAME_SUBMITTED IN ('Cytology GYN % (=< 8 days)','Breast Biopsy % (=< 3 days)','Breast Large/Resection % (=< 5 days)')) t ON t.METRIC_NAME_SUBMITTED = d.METRIC_NAME_SUBMITTED) m
LEFT JOIN (SELECT d.SERVICE AS FUNCTION, /* YTD Metric Lab */
                  REPLACE(d.METRIC_NAME_SUBMITTED,' (YTD)','') AS EXPTYPE,
                  d.REPORTING_MONTH AS MONTH,
                  t.TARGET AS YTD_TARGET,
                  d.VALUE AS YTD_ACTUAL,
                  d.VALUE - t.TARGET   AS YTD_VARIANCE_TO_TARGET,
                  d.VALUE - t.TARGET  AS YTD_PERCENT_VARIANCE
            FROM ( SELECT * FROM BSC_LAB_KPI_SYSTEM_METRICS
                   WHERE SITE = 'SYSTEM' AND
                         METRIC_NAME_SUBMITTED IN ('Cytology GYN Volume (YTD)','Cytology GYN % (=< 8 days) (YTD)','Breast Biopsy % (=< 3 days) (YTD)','Breast Biopsy Volume (YTD)','Breast Large/Resection Volume (YTD)','Breast Large/Resection % (=< 5 days) (YTD)')) d
            LEFT JOIN  (SELECT * FROM BSC_TARGET_STATUS
                        WHERE SITE = 'SYSTEM' AND
                            METRIC_NAME_SUBMITTED IN ('Cytology GYN % (=< 8 days)','Breast Biopsy % (=< 3 days)','Breast Large/Resection % (=< 5 days)')) t ON CONCAT(t.METRIC_NAME_SUBMITTED ,' (YTD)') = d.METRIC_NAME_SUBMITTED) y ON
                     y.FUNCTION = m.FUNCTION
                     AND y.EXPTYPE = m.EXPTYPE
                     AND y.MONTH = m.MONTH
;
