CREATE or replace VIEW BSC_COST_CENTER_MAPPING_VIEW AS
SELECT FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE SITE NOT IN ('HSO', 'MSO') AND NOT(FUNCTION like 'MSO:%')
UNION
SELECT CATEGORY AS FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE CATEGORY IS NOT NULL AND SITE NOT IN ('HSO', 'MSO') AND NOT(FUNCTION like 'MSO:%')
UNION
SELECT OVERLAP AS FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE OVERLAP IS NOT NULL AND SITE NOT IN ('HSO', 'MSO') AND NOT(FUNCTION like 'MSO:%')
UNION
SELECT FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE SITE = 'MSO' AND FUNCTION like 'MSO:%'

