---  CREATE VIEW BSC_COST_CENTER_MAPPING_VIEW AS
SELECT FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE OVERLAP iS NULL AND CATEGORY IS NULL
UNION
SELECT CATEGORY AS FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE CATEGORY IS NOT NULL
UNION
SELECT OVERLAP AS FUNCTION, CATEGORY, SITE, COST_CENTER, NAME FROM BSC_FINANCE_COST_CENTER_MAPPING WHERE OVERLAP IS NOT NULL

