CREATE VIEW BSC_CURRENT_FINANCE_VIEW
AS
/* Supplies and Salaries  YTD , MTD, Variance and Percent Variance */ 
SELECT a.*, (a.MTD_TARGET - a.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,  
        ROUND(((a.MTD_TARGET - a.MTD_ACTUAL)/NULLIF(a.MTD_TARGET,0)),5) AS MTD_PERCENT_VARIANCE,
        (a.YTD_TARGET - a.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
        ROUND(((a.YTD_TARGET - a.YTD_ACTUAL)/NULLIF(a.YTD_TARGET,0)),5) AS YTD_PERCENT_VARIANCE
FROM (
    SELECT Function, EXPTYPE, Month, 
    SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
    SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
    SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
    SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
    FROM BSC_FINANCE_TABLE
    WHERE EXPTYPE IN ('Salaries', 'Supplies') 
    GROUP BY Function, EXPTYPE, Month) a
UNION
/* Supplies and Salaries Combined for  YTD , MTD, Variance and Percent Variance */
SELECT b.*, (b.MTD_TARGET - b.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,  
        ROUND(((b.MTD_TARGET - b.MTD_ACTUAL)/NULLIF(b.YTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE,
        (b.YTD_TARGET - b.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
        ROUND(((b.YTD_TARGET - b.YTD_ACTUAL)/NULLIF(b.YTD_TARGET, 0)),5) AS YTD_PERCENT_VARIANCE 
FROM (
    SELECT Function, 'Total Expenses' AS EXPTYPE,Month,
    SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
    SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
    SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
    SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
    FROM BSC_FINANCE_TABLE
    WHERE EXPTYPE IN ('Salaries', 'Supplies') 
    GROUP BY Function, Month) b
UNION
SELECT c.*, (c.MTD_TARGET - c.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,  
        ROUND(((c.MTD_TARGET - c.MTD_ACTUAL)/NULLIF(c.YTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE,
        (c.YTD_TARGET - c.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
        ROUND(((c.YTD_TARGET - c.YTD_ACTUAL)/NULLIF(c.YTD_TARGET, 0)),5) AS YTD_PERCENT_VARIANCE 
FROM (
    SELECT Function, 
        CASE
          WHEN SUPPLY_MAPPING_FILE_CATEGORY = 'Agency' then 'Agency/Temp Help Dollars'
          ELSE 'OT Dollars'
        END EXPTYPE,
        Month,
        SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
        SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
        SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
        SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
    FROM BSC_FINANCE_TABLE
    WHERE SUPPLY_MAPPING_FILE_CATEGORY IN ( 'Agency','OT')   /* EXPTYPE IN ('Salaries', 'Supplies') */
    GROUP BY Function, Month,SUPPLY_MAPPING_FILE_CATEGORY) c 
UNION    
SELECT d.Function,
       'Worked Hours Productivity Index' AS EXPTYPE,
       d.MONTH,
       1.00 AS MTD_TARGET,
       d.MTD_ACTUAL,
       1.00 AS YTD_TARGET,
       d.YTD_ACTUAL,
       d.MTD_ACTUAL - 1.00 AS MTD_VARIANCE_TO_TARGET,
       d.MTD_ACTUAL - 1.00 AS MTD_PERCENT_VARIANCE,
       d.YTD_ACTUAL - 1.00 AS YTD_VARIANCE_TO_TARGET,
       d.MTD_ACTUAL - 1.00 AS YTD_PERCENT_VARIANCE
FROM (
SELECT *
FROM(
SELECT SERVICE AS Function,
      METRIC_NAME_SUBMITTED AS EXPTYPE,
      VALUE,
      REPORTING_MONTH AS MONTH
FROM BSC_SYSTEM_WIDE_PRODUCTIVITY_FINANCE)
PIVOT(
 SUM(VALUE)
 FOR EXPTYPE IN ('Worked Hours Productivity Index (FYTD)' YTD_ACTUAL,'Worked Hours Productivity Index' MTD_ACTUAL))) d;





CREATE INDEX BSCSWCS 
ON BSC_CURRENT_FINANCE_VIEW (
   FUNCTION,
   EXPTYPE,
   MONTH
);
