create or replace view OAO_DEVELOPMENT.BSC_CURRENT_FINANCE_VIEW as
SELECT a."FUNCTION",a."EXPTYPE",a."MONTH",a."MTD_TARGET",a."MTD_ACTUAL",a."YTD_TARGET",a."YTD_ACTUAL", (a.MTD_TARGET - a.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,
ROUND(((a.MTD_TARGET - a.MTD_ACTUAL)/NULLIF(a.MTD_TARGET,0)),5) AS MTD_PERCENT_VARIANCE,
(a.YTD_TARGET - a.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
ROUND(((a.YTD_TARGET - a.YTD_ACTUAL)/NULLIF(a.YTD_TARGET,0)),5) AS YTD_PERCENT_VARIANCE
FROM (
  SELECT Function, EXPTYPE, Month,
  SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
  SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
  SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
  SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
  FROM (
    SELECT a.NAME,
    a.EXPTYPE,
    a.SUB_ACCOUNT,
    a.SUB_ACCOUNT_DESCRIPTION,
    a.SUPPLY_MAPPING_FILE_CATEGORY,
    a.MONTH,
    a.SUM_OF_ANNUAL_BUDGET,
    a.SUM_OF_MONTH_ACTUAL,
    a.SUM_OF_MONTH_BUDGET,
    a.SUM_OF_REMAINING_BUDGET_YTD,
    a.SUM_OF_YTD_ACTUAL,
    a.SUM_OF_YTD_BUDGET,
    b.COST_CENTER,
    b.NAME AS CC_MAPPING_NAME,
    b.SITE,
    b.CATEGORY,
    b.FUNCTION
    FROM BSC_FINANCE_TABLE a
    LEFT JOIN BSC_COST_CENTER_MAPPING_VIEW b ON
    a.CC = b.COST_CENTER)
  WHERE EXPTYPE IN ('Salaries', 'Supplies')
  GROUP BY Function, EXPTYPE, Month) a
UNION
/* Supplies and Salaries Combined for  YTD , MTD, Variance and Percent Variance */
  SELECT b."FUNCTION",b."EXPTYPE",b."MONTH",b."MTD_TARGET",b."MTD_ACTUAL",b."YTD_TARGET",b."YTD_ACTUAL", (b.MTD_TARGET - b.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,
ROUND(((b.MTD_TARGET - b.MTD_ACTUAL)/NULLIF(b.YTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE,
(b.YTD_TARGET - b.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
ROUND(((b.YTD_TARGET - b.YTD_ACTUAL)/NULLIF(b.YTD_TARGET, 0)),5) AS YTD_PERCENT_VARIANCE
FROM (
  SELECT Function, 'Total Expenses' AS EXPTYPE,Month,
  SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
  SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
  SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
  SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
  FROM (
    SELECT a.NAME,
    a.EXPTYPE,
    a.SUB_ACCOUNT,
    a.SUB_ACCOUNT_DESCRIPTION,
    a.SUPPLY_MAPPING_FILE_CATEGORY,
    a.MONTH,
    a.SUM_OF_ANNUAL_BUDGET,
    a.SUM_OF_MONTH_ACTUAL,
    a.SUM_OF_MONTH_BUDGET,
    a.SUM_OF_REMAINING_BUDGET_YTD,
    a.SUM_OF_YTD_ACTUAL,
    a.SUM_OF_YTD_BUDGET,
    b.COST_CENTER,
    b.NAME AS CC_MAPPING_NAME,
    b.SITE,
    b.CATEGORY,
    b.FUNCTION
    FROM BSC_FINANCE_TABLE a
    LEFT JOIN BSC_COST_CENTER_MAPPING_VIEW b ON
    a.CC = b.COST_CENTER
  )
  WHERE EXPTYPE IN ('Salaries', 'Supplies')
  GROUP BY Function, Month) b
UNION
SELECT c."FUNCTION",c."EXPTYPE",c."MONTH",c."MTD_TARGET",c."MTD_ACTUAL",c."YTD_TARGET",c."YTD_ACTUAL", (c.MTD_TARGET - c.MTD_ACTUAL) AS MTD_VARIANCE_TO_TARGET,
ROUND(((c.MTD_TARGET - c.MTD_ACTUAL)/NULLIF(c.YTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE,
(c.YTD_TARGET - c.YTD_ACTUAL) AS YTD_VARIANCE_TO_TARGET,
ROUND(((c.YTD_TARGET - c.YTD_ACTUAL)/NULLIF(c.YTD_TARGET, 0)),5) AS YTD_PERCENT_VARIANCE
FROM (
  SELECT Function,
  CASE
  WHEN SUPPLY_MAPPING_FILE_CATEGORY = 'Agency' then 'Agency/Temp Help Dollars'
  ELSE 'OT Dollars'
  END EXPTYPE,
  Month,
  SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
  SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL,
  SUM(SUM_OF_YTD_BUDGET) AS YTD_TARGET,
  SUM(SUM_OF_YTD_ACTUAL) AS YTD_ACTUAL
  FROM (
    SELECT a.NAME,
    a.EXPTYPE,
    a.SUB_ACCOUNT,
    a.SUB_ACCOUNT_DESCRIPTION,
    a.SUPPLY_MAPPING_FILE_CATEGORY,
    a.MONTH,
    a.SUM_OF_ANNUAL_BUDGET,
    a.SUM_OF_MONTH_ACTUAL,
    a.SUM_OF_MONTH_BUDGET,
    a.SUM_OF_REMAINING_BUDGET_YTD,
    a.SUM_OF_YTD_ACTUAL,
    a.SUM_OF_YTD_BUDGET,
    b.COST_CENTER,
    b.NAME AS CC_MAPPING_NAME,
    b.SITE,
    b.CATEGORY,
    b.FUNCTION
    FROM BSC_FINANCE_TABLE a
    LEFT JOIN BSC_COST_CENTER_MAPPING_VIEW b ON
    a.CC = b.COST_CENTER
  )
  WHERE SUPPLY_MAPPING_FILE_CATEGORY IN ( 'Agency','OT')   /* EXPTYPE IN ('Salaries', 'Supplies') */
    GROUP BY Function, Month,SUPPLY_MAPPING_FILE_CATEGORY) c
UNION
SELECT d.Function,
'Worked Hours Productivity Index' AS EXPTYPE,
d.MONTH,
1.00 AS MTD_TARGET,
d.MTD_ACTUAL,
1.00 AS YTD_TARGET,
d.YTD_ACTUAL,
d.MTD_ACTUAL - 1.00 AS MTD_VARIANCE_TO_TARGET,
d.MTD_ACTUAL - 1.00 AS MTD_PERCENT_VARIANCE,
d.YTD_ACTUAL - 1.00 AS YTD_VARIANCE_TO_TARGET,
d.YTD_ACTUAL - 1.00 AS YTD_PERCENT_VARIANCE
FROM (
  SELECT *
    FROM(
      SELECT SERVICE AS Function,
      METRIC_NAME_SUBMITTED AS EXPTYPE,
      VALUE,
      REPORTING_MONTH AS MONTH
      FROM BSC_SYSTEM_WIDE_PRODUCTIVITY_FINANCE
    )
  PIVOT(
    SUM(VALUE)
    FOR EXPTYPE IN ('Worked Hours Productivity Index (FYTD)' YTD_ACTUAL,'Worked Hours Productivity Index' MTD_ACTUAL))) d
/
  
  