create or replace view OAO_PRODUCTION.BSC_MDF_DEMO as
SELECT a."SERVICE",a."SITE",a."REPORTING_MONTH",a."PREMIER_REPORTING_PERIOD",a."METRIC_NAME_SUBMITTED",a."VALUE",a."UPDATED_TIME",a."UPDATED_USER", b.METRIC_GROUP, b.METRIC_NAME FROM SUMMARY_REPO a
        left join bsc_mapping_table b on a.SERVICE = b.SERVICE AND a.METRIC_NAME_SUBMITTED = b.METRIC_NAME_SUBMITTED
         WHERE SITE IN ('MSQ', 'NYEE', 'MSB', 'MSBI', 'MSM', 'MSH', 'MSW') AND
               a.METRIC_NAME_SUBMITTED NOT IN ('Troponin (<=50 min)','HGB (<=60 min)')
        UNION
SELECT c.SERVICE,c.SITE,c.REPORTING_MONTH,c.PREMIER_REPORTING_PERIOD,c.METRIC_NAME_SUBMITTED,c.VALUE,c.UPDATED_TIME,c.UPDATED_USER,d.METRIC_GROUP, d.METRIC_NAME FROM BSC_LAB_KPI_METRICS c
         left join bsc_mapping_table d on c.SERVICE = d.SERVICE AND c.METRIC_NAME_SUBMITTED = d.METRIC_NAME_SUBMITTED
        WHERE SITE NOT IN ('MSSN')