CREATE OR REPLACE VIEW BSC_METRICS_FINAL_TESTING AS
SELECT d.SERVICE, c.SITE, c.REPORTING_MONTH, d.METRIC_NAME_SUBMITTED, d.METRIC_NAME_SUMMARY, d.METRIC_GROUP, c.VALUE, d.DISPLAY_ORDER, d.METRIC_UNIT, d.REPORTING_TAB, e.TARGET,
CASE WHEN c.VALUE BETWEEN e.GREEN_START AND e.GREEN_END OR c.VALUE BETWEEN e.GREEN_END AND e.GREEN_START THEN 'Green' WHEN c.VALUE BETWEEN e.YELLOW_START AND e.YELLOW_END OR c.VALUE BETWEEN e.YELLOW_END AND e.YELLOW_START THEN 'Yellow' WHEN c.VALUE BETWEEN e.RED_START AND e.RED_END OR c.VALUE BETWEEN e.RED_END AND e.RED_START THEN 'Red' ELSE 'NA' END AS TARGET_STATUS,
case WHEN d.GENERAL_GROUP = 'Premier' AND  c.METRIC_NAME_SUBMITTED != 'Overtime Dollars - % (Finance)' THEN INITCAP(CONCAT('Rep. Pd. Ending ', TO_CHAR(c.REPORTING_MONTH, 'MM/DD/YYYY'))) ELSE  INITCAP(TO_CHAR(c.REPORTING_MONTH, 'MON YYYY')) END AS CURRENT_PERIOD
FROM(
    SELECT SERVICE, SITE, REPORTING_MONTH, METRIC_NAME_SUBMITTED, VALUE FROM SUMMARY_REPO 
                WHERE SERVICE IS NOT NULL AND SITE IN ('MSQ', 'NYEE', 'MSB', 'MSBI', 'MSM', 'MSH', 'MSW') AND
               METRIC_NAME_SUBMITTED NOT IN ('Troponin (<=50 min)','HGB (<=60 min)')
    UNION           
    SELECT SERVICE, SITE, REPORTING_DATE_START AS REPORTING_MONTH, CONCAT(QUESTION_CLEAN, ' - Score') AS METRIC_NAME_SUBMITTED, SITE_MEAN AS VALUE FROM BSC_PATIENT_EXPERIENCE_REPO WHERE REPORTINGTYPE = 'Monthly'
    UNION           
    SELECT a.SERVICE, a.SITE,  REPORTING_DATE_START AS REPORTING_MONTH, CONCAT(a.QUESTION_CLEAN, ' - N') AS METRIC_NAME_SUBMITTED, a.SITE_N AS VALUE FROM BSC_PATIENT_EXPERIENCE_REPO a
               LEFT JOIN BSC_PATIENT_EXPERIENCE_MAPPING b ON a.SERVICE = b.SERVICE AND a.QUESTION_CLEAN = b.QUESTION_CLEAN
                WHERE a.REPORTINGTYPE = 'Monthly' AND b.INCL_N = 'true'
    UNION
    SELECT a.SERVICE, a.SITE, REPORTING_DATE_START AS REPORTING_MONTH, 'Rank - All Hospitals' AS METRIC_NAME_SUBMITTED, a.ALL_PG_DATABASE_RANK AS VALUE FROM BSC_PATIENT_EXPERIENCE_REPO a
                LEFT JOIN BSC_PATIENT_EXPERIENCE_MAPPING b ON a.SERVICE = b.SERVICE AND a.QUESTION_CLEAN = b.QUESTION_CLEAN
                WHERE a.REPORTINGTYPE = 'Monthly' AND b.INCL_ALLHOSP_RANK = 'true'
    UNION
    SELECT SERVICE, SITE, REPORTING_MONTH, METRIC_NAME_SUBMITTED, VALUE
                FROM BSC_LAB_KPI_METRICS
                WHERE SITE NOT IN ('MSSN')
) c
RIGHT JOIN BSC_MAPPING_TABLE d on c.SERVICE = d.SERVICE AND c.METRIC_NAME_SUBMITTED = d.METRIC_NAME_SUBMITTED
LEFT JOIN BSC_TARGET_STATUS e on c.SERVICE = e.SERVICE AND c.METRIC_NAME_SUBMITTED = e.METRIC_NAME_SUBMITTED AND c.SITE = e.SITE
WHERE d.GENERAL_GROUP != 'Budget'

UNION

SELECT d.SERVICE, case when c.SITE = 'MS STL' THEN 'MSM' WHEN c.SITE = 'MS WEST' THEN 'MSW' WHEN c.SITE = 'MS BI' THEN 'MSBI' WHEN c.SITE = 'MS NYEE' THEN 'NYEE' WHEN c.SITE = 'MS BIB' THEN 'MSB' ELSE c.SITE END AS SITE, c.REPORTING_MONTH, d.METRIC_NAME_SUBMITTED, d.METRIC_NAME_SUMMARY, 'Budget to Actual' AS METRIC_GROUP, c.VALUE, d.DISPLAY_ORDER, d.METRIC_UNIT, d.REPORTING_TAB, 0 AS TARGET,
case when MTD_PERCENT_VARIANCE <= -.02 THEN 'Red' WHEN MTD_PERCENT_VARIANCE  >-.02 AND MTD_PERCENT_VARIANCE <0 THEN 'Yellow' WHEN MTD_PERCENT_VARIANCE >= 0 THEN 'Green' ELSE 'NA' END AS TARGET_STATUS,
INITCAP(TO_CHAR(c.REPORTING_MONTH, 'MON YYYY')) AS CURRENT_PERIOD
FROM(
    SELECT a.FUNCTION AS SERVICE, a.SITE, a.MONTH AS REPORTING_MONTH, case a.EXPTYPE  WHEN 'Salaries' THEN 'Budget to Actual Variance - Labor' ELSE 'Budget to Actual Variance - Non Labor' END AS METRIC_NAME_SUBMITTED, (a.MTD_TARGET - a.MTD_ACTUAL) AS VALUE,
            ROUND(((a.MTD_TARGET - a.MTD_ACTUAL)/NULLIF(a.MTD_TARGET,0)),5) AS MTD_PERCENT_VARIANCE
    FROM (
        SELECT Function, SITE, EXPTYPE, Month,
        SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
        SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL
        FROM BSC_FINANCE_TABLE_VIEW
        WHERE EXPTYPE IN ('Salaries', 'Supplies') AND SITE IN ('MS STL', 'MS WEST', 'MSQ', 'MS BI', 'MS NYEE', 'MSH', 'MS BIB')
        GROUP BY Function, EXPTYPE, Month, SITE) a
    UNION
    /* Supplies and Salaries Combined for  YTD , MTD, Variance and Percent Variance */
    SELECT b.FUNCTION AS SERVICE, b.SITE, b.MONTH AS REPORTING_MONTH, b.EXPTYPE AS METRIC_NAME_SUBMITTED, (b.MTD_TARGET - b.MTD_ACTUAL) AS VALUE,
            ROUND(((b.MTD_TARGET - b.MTD_ACTUAL)/NULLIF(b.MTD_TARGET, 0)),5) AS MTD_PERCENT_VARIANCE
    FROM (
        SELECT Function, SITE, 'Budget to Actual Variance - Total' AS EXPTYPE,Month,
        SUM(SUM_OF_MONTH_BUDGET) AS MTD_TARGET,
        SUM(SUM_OF_MONTH_ACTUAL) AS MTD_ACTUAL
        FROM BSC_FINANCE_TABLE_VIEW
        WHERE EXPTYPE IN ('Salaries', 'Supplies') AND SITE IN ('MS STL', 'MS WEST', 'MSQ', 'MS BI', 'MS NYEE', 'MSH', 'MS BIB')
        GROUP BY Function, Month, SITE) b
) c
RIGHT JOIN BSC_MAPPING_TABLE d on c.SERVICE = d.SERVICE AND (c.METRIC_NAME_SUBMITTED = d.METRIC_NAME_SUBMITTED or d.METRIC_NAME_SUBMITTED = CONCAT(c.METRIC_NAME_SUBMITTED, ' (Monthly)'))
WHERE d.GENERAL_GROUP = 'Budget' AND c.SITE IS NOT NULL;
